name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build solver
        shell: bash
        run: |
          sudo apt-get -y install libboost-all-dev
          mkdir build_skyline
          cd build_skyline
          cmake ..
          make
      - name: install dependencies
        run: |
          pip install pytest pytest-cov pytest-mock pytest-xdist
          pip install numpy
      - name: result simulation system tests
        run: |
          # We're providing the path to the EXE based on the prior build solver step.
          pytest Tests/SystemTests -n auto --relativeExePath="build_skyline/bin/OneDSolver" 
      - name: result unit tests 
        run: |
          cd build_skyline
          ctest
